name: CI Workflow
on:
  push:
    branches:
      - development
env:
  REGION: us-central1
  GKE_CLUSTER: gatherup-ui-cluster
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for GAR
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build \
          -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/gatherup-ui .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GAR_REPO }}/gatherup-ui

      - name: Set up GKE SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'

      - name: Authenticate to GKE
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.REGION }}

      - name: Prepare deployment.yaml
        run: |
          sed "s|REGION|${{ env.REGION }}|g; \
               s|PROJECT_ID|${{ secrets.GCP_PROJECT_ID }}|g; \
               s|REPO_NAME|${{ secrets.GAR_REPO }}|g; \
               s|IMAGE_NAME|gatherup-ui|g; \
               s|TAG|latest|g" \
               s|PLACEHOLDER|$(date +%s)|g" \
               k8s/deployment.template.yaml > k8s/deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
